# This is a basic workflow to help you get started with Actions

name: UseGitVersionToOutput

# Controls when the workflow will run
on: 
  pull_request: 
    branches:
      - main
  push:
    branches:
      #- main
        #push on main
      - 'release/**'
      - 'feature/**'
      - 'dev/**'
      - 'hotfix/**'
      - 'bug/**'
        #push on feature branch with prefix release
  
  #merge on main or practically main push
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  calculate-version:
    name: Calculate Version
    runs-on: ubuntu-latest
    outputs:
      fullSemVer: ${{ steps.gitversion.outputs.fullSemVer }} # To use an output in another job, you have to map it to a job output.
      branchName: ${{ steps.gitversion.outputs.branchName }} # To use an output in another job, you have to map it to a job output.
    steps:
      # gitversion/execute step omitted for brevity
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - run: |
            #Output variables can also be accessed in steps, using an expression.
            echo "Version: ${{ steps.gitversion.outputs.fullSemVer }}."
            echo "BranchName: ${{ steps.gitversion.outputs.branchName }}."
        
  release:
      runs-on: ubuntu-latest
      needs: calculate-version
      if: contains(needs.calculate-version.outputs.branchName, 'main') # Output variable accessed via `needs` context.
      steps:
        - name: Create GitHub release
          uses: Roang-zero1/github-create-release-action@master
          with:
            #version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
            created_tag: ${{ needs.calculate-version.outputs.fullSemVer }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - run: |
            #Output variables can also be accessed in steps, using an expression.
            echo "Creating release notes for version: ${{ needs.calculate-version.outputs.fullSemVer }}."
            
